const symbols=['🪙','⚓','☠️','🏴‍☠️','💎','🦜','🐙','🧭','💰','🌴','🍹','🚢','🦈','🐚','⭐','🔱','🏝️','🗝️','💀','🌊'];
const names=['Île du Départ','Baie des Palmiers','Île du Kraken','Fort des Flibustiers','Île au Trésor'];
const counts=[0,48,64,80,96,120];
const difficulties=['','Facile','Moyen','Difficile','Très difficile','Expert'];
const goals=[0,1200,1800,2400,3000,4200];
const TILE_W=58,TILE_H=70,STEP_X=54,STEP_Y=62;
let state=JSON.parse(localStorage.getItem('mahjongPirateState')||'null')||{coins:0,gems:0,level:1,xp:0,bestScore:0,unlocked:1};
let game=null,timer=null,startedAt=0;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('mahjongPirateState',JSON.stringify(state));updateHud()}
function updateHud(){if(!$('coins'))return;$('coins').textContent=state.coins;$('gems').textContent=state.gems;$('captainName').textContent=state.level<3?'Mousse des Caraïbes':state.level<5?'Capitaine Corsaire':'Maître des Sept Mers';$('level').textContent=state.level;$('xp').textContent=state.xp;$('bestScore').textContent=state.bestScore;$('mapProgress').textContent=`${state.unlocked}/5`;document.querySelectorAll('.island').forEach((b,i)=>{b.classList.toggle('locked',i+1>state.unlocked);b.classList.toggle('current',i+1===state.unlocked)})}
function rectOverlap(a,b){return a.x<b.x+TILE_W&&a.x+TILE_W>b.x&&a.y<b.y+TILE_H&&a.y+TILE_H>b.y}
function rectOverlapY(a,b){return a.y<b.y+TILE_H&&a.y+TILE_H>b.y}
function freeTile(t,tiles){if(t.removed)return false;for(const o of tiles)if(!o.removed&&o.l>t.l&&rectOverlap(t,o))return false;let left=false,right=false;for(const o of tiles){if(o.removed||o.l!==t.l||o.id===t.id||!rectOverlapY(t,o))continue;if(o.x<t.x&&o.x+TILE_W>t.x)left=true;if(o.x<t.x+TILE_W&&o.x+TILE_W>t.x+TILE_W)right=true}return !(left&&right)}
function layout(level){const shapes={1:[6,8,10,10,8,6],2:[6,8,10,12,12,10,6],3:[6,8,10,12,14,12,10,8],4:[8,10,12,14,14,12,10,8,8],5:[8,10,14,16,18,16,14,10,8,6]};const rows=shapes[level],positions=[];rows.forEach((width,r)=>{const start=(18-width)/2;for(let c=0;c<width;c++)positions.push({x:18+(start+c)*STEP_X,y:18+r*STEP_Y,l:0})});if(level>=2){const raised=level===2?18:level===3?28:level===4?38:50;let made=0;for(let r=2;r<rows.length-2&&made<raised;r++){const row=positions.filter(p=>Math.round((p.y-18)/STEP_Y)===r);for(let i=1;i<row.length-1&&made<raised;i+=2){row[i].l=1;row[i].x+=11;row[i].y-=9;made++}}}if(level>=3){const center=positions.filter(p=>p.l===0).sort((a,b)=>Math.abs(a.x-420)-Math.abs(b.x-420)).slice(0,Math.min(10,level*2));center.forEach(p=>{p.l=2;p.x+=22;p.y-=18})}return positions.map((p,i)=>({...p,id:i}))}
function buildSolvable(level){for(let attempt=0;attempt<700;attempt++){const positions=layout(level),remaining=positions.map(p=>({...p,removed:false})),pairs=[];while(remaining.some(t=>!t.removed)){let free=remaining.filter(t=>freeTile(t,remaining));if(free.length<2)break;free.sort(()=>Math.random()-.5);const a=free[0],candidates=free.filter(t=>t.id!==a.id);if(!candidates.length)break;const b=candidates[Math.floor(Math.random()*candidates.length)];a.removed=b.removed=true;pairs.push([a.id,b.id])}if(pairs.length===counts[level]/2){const tiles=positions.map(p=>({...p,removed:false,symbol:null}));pairs.forEach(([a,b],i)=>{const s=symbols[i%symbols.length];tiles[a].symbol=s;tiles[b].symbol=s});return tiles}}const positions=layout(level);return positions.map((p,i)=>({...p,removed:false,symbol:symbols[Math.floor(i/2)%symbols.length]}))}
function symbolKind(s){const i=symbols.indexOf(s);return i<0?'unknown':`kind-${i}`}
function newGame(level){clearInterval(timer);closeDeadlock();game={level,tiles:buildSolvable(level),selected:null,score:0,moves:0,pairs:0,combo:0,bestCombo:0,undo:[],shuffles:0};startedAt=Date.now();$('map').classList.add('hidden');$('game').classList.remove('hidden');$('islandTitle').textContent=names[level];$('difficulty').textContent=difficulties[level];$('msg').textContent=`🏴‍☠️ ${counts[level]} tuiles — retire toutes les paires.`;render();timer=setInterval(tick,500)}
function tick(){if(!game)return;const sec=Math.floor((Date.now()-startedAt)/1000);$('time').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function updateTargets(){if(!game)return;const g=goals[game.level];if($('goal1'))$('goal1').textContent=Math.round(g*.3);if($('goal2'))$('goal2').textContent=Math.round(g*.6);if($('goal3'))$('goal3').textContent=g;if($('goalBar'))$('goalBar').style.width=Math.min(100,(game.score/g)*100)+'%'}
function render(){const board=$('board');board.innerHTML='';board.style.width=levelWidth(game.level)+'px';board.style.height=levelHeight(game.level)+'px';for(const t of game.tiles){if(t.removed)continue;const free=freeTile(t,game.tiles),b=document.createElement('button');b.className='tile '+(free?'free':'blocked')+' '+symbolKind(t.symbol);if(game.selected===t.id)b.classList.add('selected');b.textContent=t.symbol;b.style.left=t.x+'px';b.style.top=t.y+'px';b.style.zIndex=20+t.l;b.dataset.kind=symbolKind(t.symbol);b.onclick=()=>pick(t.id);board.appendChild(b)}$('score').textContent=game.score;$('remaining').textContent=game.tiles.filter(t=>!t.removed).length;$('moves').textContent=game.moves;$('pairs').textContent=game.pairs;updateTargets();updateBoosters()}
function levelWidth(l){return l<=1?850:l===2?920:l===3?980:l===4?1040:1100}
function levelHeight(l){return l<=2?650:l===3?720:l===4?780:840}
function legalPairs(){const free=game.tiles.filter(t=>!t.removed&&freeTile(t,game.tiles)),out=[];for(let i=0;i<free.length;i++)for(let j=i+1;j<free.length;j++)if(free[i].symbol===free[j].symbol)out.push([free[i],free[j]]);return out}
function showDeadlock(){if(!game||game.tiles.every(t=>t.removed)||legalPairs().length)return;clearInterval(timer);$('deadlockText').textContent=`Il reste ${game.tiles.filter(t=>!t.removed).length} tuiles, mais aucune paire libre n'est actuellement disponible.`;$('deadlock').showModal();sfx(false)}
function closeDeadlock(){if($('deadlock')?.open)$('deadlock').close()}
function pick(id){if($('deadlock')?.open)closeDeadlock();const t=game.tiles.find(x=>x.id===id);if(!t||!freeTile(t,game.tiles))return;if(game.selected===null){game.selected=id;render();return}const a=game.tiles.find(x=>x.id===game.selected);game.moves++;if(a&&a.id!==t.id&&a.symbol===t.symbol&&freeTile(a,game.tiles)){game.undo.push({a:a.id,b:t.id,score:game.score,combo:game.combo});a.removed=t.removed=true;game.pairs++;game.combo++;game.bestCombo=Math.max(game.bestCombo,game.combo);const gain=100+game.level*20+Math.max(0,game.combo-1)*25;game.score+=gain;game.selected=null;sfx(true);$('msg').textContent=game.combo>=3?`🔥 Combo x${game.combo} ! +${gain} points.`:'⚓ Bonne prise ! Paire retirée.'}else{game.combo=0;game.selected=null;sfx(false);$('msg').textContent='❌ Paire impossible : deux symboles identiques et libres.'}render();if(game.tiles.every(t=>t.removed))win();else if(!legalPairs().length)showDeadlock()}
function hint(){if(!game)return;const pair=legalPairs()[0];if(pair){game.selected=pair[0].id;game.score=Math.max(0,game.score-10);render();$('msg').textContent=`💡 Indice : ${pair[0].symbol} possède une paire libre.`}else showDeadlock()}
function shuffle(){if(!game)return;closeDeadlock();const active=game.tiles.filter(t=>!t.removed),original=active.map(t=>t.symbol);let ok=false;for(let attempt=0;attempt<100&&!ok;attempt++){const syms=[...original].sort(()=>Math.random()-.5);active.forEach((t,i)=>t.symbol=syms[i]);ok=legalPairs().length>0}if(!ok)active.forEach((t,i)=>t.symbol=original[i]);game.score=Math.max(0,game.score-35);game.combo=0;game.selected=null;game.shuffles++;render();$('msg').textContent=ok?'🔀 Les cartes ont été remélangées.':'🔀 Le mélange n’a rien débloqué.';timer=setInterval(tick,500)}
function undo(){if(!game||!game.undo.length){$('msg').textContent='↩️ Aucun coup à annuler.';return}const u=game.undo.pop(),a=game.tiles.find(t=>t.id===u.a),b=game.tiles.find(t=>t.id===u.b);if(a&&b){a.removed=false;b.removed=false;game.score=u.score;game.combo=u.combo;game.pairs=Math.max(0,game.pairs-1);game.moves++;game.selected=null;render();$('msg').textContent='↩️ Dernière paire restaurée.'}}
function bomb(){if(!game)return;const pair=legalPairs()[0];if(!pair){showDeadlock();return}pair.forEach(t=>t.removed=true);game.pairs++;game.score+=80;game.selected=null;render();$('msg').textContent='💣 Canon pirate ! Une paire a été pulvérisée.';if(game.tiles.every(t=>t.removed))win()}
function updateBoosters(){if(!$('undoCount'))return;$('undoCount').textContent=game?.undo?.length||0;$('shuffleCount').textContent=game?.shuffles||0}
function win(){clearInterval(timer);closeDeadlock();const sec=Math.floor((Date.now()-startedAt)/1000),g=goals[game.level],stars=game.score>=g?3:game.score>=g*.6?2:1,reward=25*game.level+stars*10,xp=30*game.level+stars*12;state.coins+=reward;state.xp+=xp;state.level=Math.max(state.level,Math.min(5,1+Math.floor(state.xp/100)));if(game.score>state.bestScore)state.bestScore=game.score;if(game.level===state.unlocked&&state.unlocked<5)state.unlocked++;save();$('winText').textContent=`Île terminée en ${sec}s avec ${game.moves} coups et ${game.bestCombo} de combo.`;$('stars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('rewardCoins').textContent=reward;$('rewardXp').textContent=xp;$('next').textContent=game.level<5?'Île suivante':'Retour à la carte';$('next').onclick=()=>{$('win').close();if(game.level<5)newGame(game.level+1);else home()};$('win').showModal();sfx(true)}
function home(){clearInterval(timer);closeDeadlock();game=null;$('game').classList.add('hidden');$('map').classList.remove('hidden');$('msg').textContent='';updateHud()}
function sfx(ok){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?660:180;g.gain.value=.04;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.09)}catch(e){}}
document.querySelectorAll('.island').forEach(b=>b.onclick=()=>{const l=+b.dataset.level;if(l<=state.unlocked)newGame(l)});$('hint').onclick=hint;$('shuffle').onclick=shuffle;$('restart').onclick=()=>game&&newGame(game.level);$('homeBtn').onclick=home;$('homeWin').onclick=()=>{$('win').close();home()};$('deadlockShuffle').onclick=shuffle;$('deadlockRestart').onclick=()=>game&&newGame(game.level);if($('undo'))$('undo').onclick=undo;if($('bomb'))$('bomb').onclick=bomb;$('resetProgress').onclick=()=>{if(confirm('Réinitialiser toute la progression ?')){localStorage.removeItem('mahjongPirateState');state={coins:0,gems:0,level:1,xp:0,bestScore:0,unlocked:1};save()}};updateHud();