const symbols=['🪙','⚓','☠️','🏴‍☠️','💎','🦜','🐙','🧭','💰','🌴','🍹','🚢','🦈','🐚','⭐','🔱','🏝️','🗝️','💀','🌊'];
const names=['Île du Départ','Baie des Palmiers','Île du Kraken','Fort des Flibustiers','Île au Trésor'];
const counts=[0,24,28,32,36,40];
const difficulties=['','Facile','Facile','Moyen','Difficile','Expert'];
let state=JSON.parse(localStorage.getItem('mahjongPirateState')||'null')||{coins:0,gems:0,level:1,xp:0,bestScore:0,unlocked:1};
let game=null,timer=null,startedAt=0;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('mahjongPirateState',JSON.stringify(state));updateHud()}
function updateHud(){$('coins').textContent=state.coins;$('gems').textContent=state.gems;$('captainName').textContent=state.level<3?'Mousse des Caraïbes':state.level<5?'Capitaine Corsaire':'Maître des Sept Mers';$('level').textContent=state.level;$('xp').textContent=state.xp;$('bestScore').textContent=state.bestScore;$('mapProgress').textContent=`${state.unlocked}/5`;document.querySelectorAll('.island').forEach((b,i)=>{b.classList.toggle('locked',i+1>state.unlocked);b.classList.toggle('current',i+1===state.unlocked)})}
function layout(level){const target=counts[level], cols=8, rows=Math.ceil(target/cols), positions=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)if(positions.length<target)positions.push({x:55+c*68+(r%2?10:0),y:35+r*78,l:0});if(level>=3){const n=Math.min(4,target-24);for(let i=0;i<n;i++){const p=positions[12+i*2];p.l=1;p.x+=12;p.y+=10}}return positions.map((p,i)=>({...p,id:i}))}
function freeTile(t,tiles){if(t.removed)return false;const sameLayer=tiles.filter(o=>!o.removed&&o.l===t.l&&o.id!==t.id);for(const o of sameLayer){const overlap=Math.abs(o.x-t.x)<48&&Math.abs(o.y-t.y)<58;if(overlap&&o.y===t.y&&o.x>t.x)return false;if(overlap&&o.y===t.y&&o.x<t.x)return false}for(const o of tiles){if(o.removed||o.l<=t.l)continue;if(Math.abs(o.x-t.x)<48&&Math.abs(o.y-t.y)<58)return false}return true}
function newGame(level){clearInterval(timer);const pos=layout(level);let seq=[];for(let i=0;i<pos.length;i+=2){const s=symbols[(i/2)%symbols.length];seq.push(s,s)}game={level,tiles:pos.map((p,i)=>({...p,symbol:seq[i],removed:false})),selected:null,score:0,moves:0,pairs:0};startedAt=Date.now();$('map').classList.add('hidden');$('game').classList.remove('hidden');$('islandTitle').textContent=names[level];$('difficulty').textContent=difficulties[level];render();timer=setInterval(tick,500)}
function tick(){if(!game)return;const sec=Math.floor((Date.now()-startedAt)/1000);$('time').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function render(){const board=$('board');board.innerHTML='';board.style.width=levelWidth(game.level)+'px';board.style.height=game.level>=4?'610px':'560px';for(const t of game.tiles){if(t.removed)continue;const b=document.createElement('button');b.className='tile '+(freeTile(t,game.tiles)?'free':'blocked');if(game.selected===t.id)b.classList.add('selected');b.textContent=t.symbol;b.style.left=t.x+'px';b.style.top=t.y+'px';b.style.zIndex=10+t.l;b.onclick=()=>pick(t.id);board.appendChild(b)}$('score').textContent=game.score;$('remaining').textContent=game.tiles.filter(t=>!t.removed).length;$('moves').textContent=game.moves;$('pairs').textContent=game.pairs}
function levelWidth(l){return l<=2?650:l===3?720:l===4?800:850}
function pick(id){const t=game.tiles.find(x=>x.id===id);if(!t||!freeTile(t,game.tiles))return;if(game.selected===null){game.selected=id;render();return}const a=game.tiles.find(x=>x.id===game.selected);game.moves++;if(a&&a.id!==t.id&&a.symbol===t.symbol&&freeTile(a,game.tiles)){a.removed=t.removed=true;game.pairs++;game.score+=100+game.level*15;game.selected=null;sfx(true);$('msg').textContent='Belle paire, capitaine !';}else{game.selected=null;sfx(false);$('msg').textContent='Ces deux tuiles ne forment pas une paire.'}render();if(game.tiles.every(t=>t.removed))win()}
function hint(){if(!game)return;const free=game.tiles.filter(t=>!t.removed&&freeTile(t,game.tiles));let found=null;outer:for(let i=0;i<free.length;i++)for(let j=i+1;j<free.length;j++)if(free[i].symbol===free[j].symbol){found=[free[i].id,free[j].id];break outer}if(found){game.selected=found[0];render();$('msg').textContent='💡 Une paire disponible est éclairée.';game.score=Math.max(0,game.score-10)}else $('msg').textContent='Aucune paire visible : mélange le plateau.'}
function shuffle(){if(!game)return;const active=game.tiles.filter(t=>!t.removed);const syms=active.map(t=>t.symbol).sort(()=>Math.random()-.5);active.forEach((t,i)=>t.symbol=syms[i]);game.score=Math.max(0,game.score-25);game.selected=null;render();$('msg').textContent='🔀 Les symboles ont été mélangés.'}
function win(){clearInterval(timer);const sec=Math.floor((Date.now()-startedAt)/1000),stars=sec<=90?3:sec<=180?2:1;const reward=20*game.level+stars*5,xp=25*game.level+stars*10;state.coins+=reward;state.xp+=xp;state.level=Math.max(state.level,Math.min(5,1+Math.floor(state.xp/100)));if(game.score>state.bestScore)state.bestScore=game.score;if(game.level===state.unlocked&&state.unlocked<5)state.unlocked++;save();$('winText').textContent=`Île terminée en ${sec}s avec ${game.moves} coups.`;$('stars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('rewardCoins').textContent=reward;$('rewardXp').textContent=xp;$('next').textContent=game.level<5?'Île suivante':'Retour à la carte';$('next').onclick=()=>{ $('win').close(); if(game.level<5)newGame(game.level+1);else home()};$('win').showModal();sfx(true)}
function home(){clearInterval(timer);game=null;$('game').classList.add('hidden');$('map').classList.remove('hidden');$('msg').textContent='';updateHud()}
function sfx(ok){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?660:180;g.gain.value=.04;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.09)}catch(e){}}
document.querySelectorAll('.island').forEach(b=>b.onclick=()=>{const l=+b.dataset.level;if(l<=state.unlocked)newGame(l)});$('hint').onclick=hint;$('shuffle').onclick=shuffle;$('restart').onclick=()=>newGame(game.level);$('homeBtn').onclick=home;$('homeWin').onclick=()=>{$('win').close();home()};$('resetProgress').onclick=()=>{if(confirm('Réinitialiser toute la progression ?')){localStorage.removeItem('mahjongPirateState');state={coins:0,gems:0,level:1,xp:0,bestScore:0,unlocked:1};save()}};updateHud();
