(function(){
 const KEY='mahjongPirateArsenal';
 const TITLES=[{level:1,icon:'🪶',name:'Mousse des Caraïbes'},{level:2,icon:'⚓',name:'Matelot des mers'},{level:3,icon:'🗺️',name:'Navigateur pirate'},{level:4,icon:'🏴‍☠️',name:'Capitaine Corsaire'},{level:5,icon:'💀',name:'Maître des Sept Mers'}];
 const ITEMS=[{id:'compass',icon:'🧭',name:'Boussole d’Azur',desc:'Réduit le coût d’un indice.',cost:3},{id:'map',icon:'🗺️',name:'Carte porte-bonheur',desc:'Protège une partie contre un mélange payant.',cost:3},{id:'crown',icon:'👑',name:'Couronne du Kraken',desc:'Titre prestigieux débloqué au niveau 5.',cost:0}];
 let data=load();
 function load(){try{return Object.assign({owned:{},title:null},JSON.parse(localStorage.getItem(KEY)||'null')||{});}catch(e){return {owned:{},title:null}}}
 function saveA(){localStorage.setItem(KEY,JSON.stringify(data));}
 function bindControls(){document.querySelectorAll('#hint').forEach(b=>b.onclick=hint);document.querySelectorAll('#shuffle').forEach(b=>b.onclick=shuffle);document.querySelectorAll('#restart').forEach(b=>b.onclick=()=>game&&newGame(game.level));}
 function inject(){if(document.getElementById('arsenalPanel'))return;const s=document.createElement('style');s.textContent=`#arsenalPanel{margin-top:14px;border:1px solid #9c6a2c;border-radius:18px;background:linear-gradient(145deg,#ead19a,#f8e9c2);overflow:hidden;box-shadow:0 10px 24px #2a170a22;color:#422719}#arsenalPanel .ah{display:flex;justify-content:space-between;align-items:center;padding:13px 15px 8px}#arsenalPanel h2{margin:0;font-size:1.05rem}#arsenalPanel .title{font-size:.72rem;opacity:.75;margin-top:3px}.arsenal-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;padding:0 10px 11px}.gear{background:#fff8e9;border:1px solid #9c6a2c88;border-radius:13px;padding:10px;min-height:110px}.gear.locked{opacity:.58;filter:saturate(.65)}.gear-icon{font-size:1.5rem}.gear strong{display:block;font-size:.82rem;margin:3px 0}.gear small{display:block;font-size:.67rem;line-height:1.25;min-height:30px}.gear button{margin-top:7px;border:1px solid #b98232;background:#174b59;color:#f8e7b1;border-radius:8px;padding:5px 8px;font-weight:800;cursor:pointer}.gear .owned{color:#286d45;font-weight:800;font-size:.7rem}@media(max-width:720px){.arsenal-grid{grid-template-columns:1fr 1fr}}
.tile{will-change:transform,opacity,filter}.tile.selected{animation:pirateSelect .65s ease-in-out infinite alternate}.tile.removing{animation:pirateRemove .32s cubic-bezier(.2,.8,.3,1) forwards!important}.tile.newly-free{animation:pirateFree .45s ease-out both!important}.board{perspective:900px}.tile[data-layer="1"]{filter:brightness(.98) drop-shadow(2px 3px 2px #00151a88)}.tile[data-layer="2"]{filter:brightness(.94) drop-shadow(3px 4px 3px #00151aaa)}.tile[data-layer="3"]{filter:brightness(.9) drop-shadow(4px 5px 4px #00151acc)}.tile[data-layer="4"]{filter:brightness(.86) drop-shadow(5px 6px 5px #00151add)}@keyframes pirateSelect{from{transform:translateY(-5px) scale(1.03)}to{transform:translateY(-9px) scale(1.06)}}@keyframes pirateRemove{0%{opacity:1;transform:scale(1)}45%{opacity:1;transform:scale(1.14) rotate(-4deg);filter:brightness(1.5) drop-shadow(0 0 10px #f5d46b)}100%{opacity:0;transform:scale(.45) rotate(10deg);filter:brightness(1.8)}}@keyframes pirateFree{0%{transform:translateY(5px) scale(.94);filter:brightness(.55)}55%{transform:translateY(-6px) scale(1.07);filter:brightness(1.3)}100%{transform:none;filter:brightness(1)}}@media(max-width:600px){#arsenalPanel{display:none}.tile{width:58px;height:70px;font-size:1.5rem;-webkit-tap-highlight-color:transparent}.board{box-shadow:inset 0 0 45px #021d29,0 12px 25px #001a24cc}.boosters button{transform:translateZ(0);transition:transform .12s ease,filter .12s ease}.boosters button:active{transform:scale(.94) translateY(2px)}}@media(prefers-reduced-motion:reduce){.tile,.boosters button{animation:none!important;transition:none!important}}`;document.head.appendChild(s);const p=document.createElement('section');p.id='arsenalPanel';p.innerHTML='<div class="ah"><div><h2>⚔️ Arsenal du capitaine</h2><div id="titleText" class="title"></div></div><span>💎</span></div><div id="arsenalGrid" class="arsenal-grid"></div>';const captain=document.querySelector('.captain-card');(captain||document.querySelector('.shell')).insertAdjacentElement('afterend',p);refresh();}
 function refresh(){const grid=document.getElementById('arsenalGrid');if(!grid)return;const lvl=Number(state.level)||1,title=data.title||TITLES[Math.min(4,lvl-1)];document.getElementById('titleText').textContent=title.icon+' Titre : '+title.name;grid.innerHTML=ITEMS.map(i=>{const owned=!!data.owned[i.id],locked=i.id==='crown'&&lvl<5;return `<article class="gear ${locked?'locked':''}"><span class="gear-icon">${i.icon}</span><strong>${i.name}</strong><small>${i.desc}</small>${locked?'<span class="owned">🔒 Niveau 5</span>':owned?'<span class="owned">✓ Possédé</span>':i.cost?`<button data-buy="${i.id}">Acheter · ${i.cost} 💎</button>`:'<span class="owned">✓ Débloqué</span>'}</article>`}).join('');grid.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy));}
 function buy(id){const item=ITEMS.find(x=>x.id===id);if(!item||data.owned[id])return;if((Number(state.gems)||0)<item.cost){alert('💎 Pas assez de gemmes pour cet équipement.');return}state.gems-=item.cost;data.owned[id]=true;saveA();if(typeof save==='function')save();refresh();if(typeof sfx==='function')sfx(true);}
 function init(){bindControls();inject();}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();