(function(){
  const $=id=>document.getElementById(id);
  const state=()=>{try{return JSON.parse(localStorage.getItem('mahjongPirateState')||'null')||{level:1,xp:0,unlocked:1,coins:0,gems:0}}catch(e){return {level:1,xp:0,unlocked:1,coins:0,gems:0}}};
  let classicPromise=null;
  function ensureClassic(){
    if(typeof window.startClassicMahjong==='function')return Promise.resolve();
    if(classicPromise)return classicPromise;
    classicPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='classic-mahjong.js?v=20260908-1';s.onload=()=>resolve();s.onerror=reject;document.head.appendChild(s)});
    return classicPromise;
  }
  function boot(){
    const home=$('home');if(!home)return;
    const map=()=>$('map'),game=()=>$('game');
    const currentLevel=()=>{const c=document.querySelector('.island.current');return c?Number(c.dataset.level)||1:1};
    const start=(level)=>{home.classList.add('hidden');map()?.classList.add('hidden');game()?.classList.remove('hidden');if(typeof window.newGame==='function')window.newGame(level)};
    const startClassic=()=>{home.classList.add('hidden');map()?.classList.add('hidden');game()?.classList.remove('hidden');ensureClassic().then(()=>window.startClassicMahjong?.()).catch(()=>{if(typeof window.newGame==='function')window.newGame(1)})};
    const homeView=()=>{if(typeof window.home==='function')window.home();map()?.classList.add('hidden');game()?.classList.add('hidden');home.classList.remove('hidden');closePanel();home.scrollIntoView({behavior:'smooth',block:'start'})};
    const mapView=()=>{home.classList.add('hidden');game()?.classList.add('hidden');map()?.classList.remove('hidden');closePanel();map()?.scrollIntoView({behavior:'smooth',block:'start'})};
    document.querySelectorAll('[data-start-level]').forEach(b=>{if(b.id!=='dailyPlay2')b.addEventListener('click',()=>{if(Number(b.dataset.startLevel)===1&&b.closest('.mode-card'))startClassic();else start(Number(b.dataset.startLevel)||1)})});
    document.querySelectorAll('[data-open-map]').forEach(b=>b.addEventListener('click',mapView));
    document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',homeView));
    $('homeBtn')?.addEventListener('click',homeView);
    $('dailyPlay')?.addEventListener('click',()=>start(currentLevel()));
    $('dailyPlay2')?.addEventListener('click',()=>start(currentLevel()));
    $('hint2')?.addEventListener('click',()=>window.hint?.());
    $('shuffle2')?.addEventListener('click',()=>window.shuffle?.());
    $('resetProgress')?.addEventListener('click',()=>{if(confirm('Réinitialiser toute la progression ?')){['mahjongPirateState','mahjongPirateProgression','mahjongPirateMissions','mahjongPirateArsenal'].forEach(k=>localStorage.removeItem(k));location.reload()}});
    decorateScene();bindSideMenu();installPanelStyle();
  }
  function bindSideMenu(){document.querySelectorAll('.side-btn').forEach(btn=>{const label=btn.textContent.replace(/\s+/g,' ').trim().toLowerCase();btn.addEventListener('click',()=>{document.querySelectorAll('.side-btn').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(label.includes('accueil'))goHome();else if(label.includes('mode'))showMap();else if(label.includes('défi')||label.includes('defi'))showDaily();else if(label.includes('collection'))showCollection();else if(label.includes('boutique'))showShop()})})}
  function goHome(){if(typeof window.home==='function')window.home();$('map')?.classList.add('hidden');$('game')?.classList.add('hidden');$('home')?.classList.remove('hidden');closePanel();}
  function showMap(){$('home')?.classList.add('hidden');$('game')?.classList.add('hidden');$('map')?.classList.remove('hidden');closePanel()}
  function showDaily(){goHome();setTimeout(()=>$('dailyPlay')?.focus(),80)}
  function panel(){let p=$('piratePanel');if(p)return p;p=document.createElement('section');p.id='piratePanel';p.innerHTML='<div class="pp-head"><div><small>QUARTIER DU CAPITAINE</small><h2></h2></div><button id="ppClose" type="button">✕</button></div><div id="ppBody"></div>';document.body.appendChild(p);$('ppClose').onclick=closePanel;return p}
  function open(title,body){const p=panel();installPanelStyle();p.querySelector('h2').textContent=title;$('ppBody').innerHTML=body;p.classList.remove('hidden')}
  function closePanel(){$('piratePanel')?.classList.add('hidden')}
  function showCollection(){const s=state(),u=Math.max(1,Math.min(15,Number(s.unlocked)||1)),l=Number(s.level)||1;const titles=[['🪶','Mousse des Caraïbes',1],['⚓','Matelot des mers',2],['🗺️','Navigateur pirate',3],['🏴‍☠️','Capitaine Corsaire',4],['💀','Maître des Sept Mers',5]];open('Collection pirate',`<div class="pp-grid"><article class="pp-card"><b class="pp-big">🏝️</b><b>Archipel</b><small>${u}/15 îles accessibles</small></article><article class="pp-card"><b class="pp-big">⭐</b><b>Capitaine</b><small>Niveau ${l} · ${s.xp||0} XP</small></article><article class="pp-card"><b class="pp-big">💰</b><b>Trésor</b><small>${s.coins||0} pièces · ${s.gems||0} gemmes</small></article></div><div class="pp-grid">${titles.map(t=>`<article class="pp-card"><b class="pp-big">${t[0]}</b><b>${t[1]}</b><small>${l>=t[2]?'✓ Disponible':'🔒 Niveau '+t[2]}</small></article>`).join('')}</div><button class="pp-action blue" id="ppArsenal">⚓ Ouvrir l’arsenal</button>`);$('ppArsenal').onclick=()=>{closePanel();document.querySelector('#arsenalPanel')?.scrollIntoView({behavior:'smooth',block:'center'})}}
  function showShop(){const s=state();open('Boutique du port',`<div class="pp-grid"><article class="pp-card"><b class="pp-big">🧭</b><b>Boussole d’Azur</b><small>Réduit le coût d’un indice.</small></article><article class="pp-card"><b class="pp-big">🗺️</b><b>Carte porte-bonheur</b><small>Protection contre un mélange payant.</small></article><article class="pp-card"><b class="pp-big">👑</b><b>Couronne du Kraken</b><small>Titre prestigieux du capitaine.</small></article></div><div class="pp-card pp-treasure"><b>💰 ${s.coins||0} pièces · 💎 ${s.gems||0} gemmes</b><small>Les achats et équipements sont centralisés dans l’arsenal.</small><br><button class="pp-action" id="ppArsenal2">⚓ Ouvrir l’arsenal</button></div>`);$('ppArsenal2').onclick=()=>{closePanel();document.querySelector('#arsenalPanel')?.scrollIntoView({behavior:'smooth',block:'center'})}}
  function decorateScene(){const scene=document.querySelector('.home-scene');if(!scene||scene.querySelector('.pirate-decor'))return;const d=document.createElement('div');d.className='pirate-decor';d.innerHTML='<span class="sun">☀️</span><span class="bird">🕊️　🕊️</span><span class="ship">🚢</span><span class="palm">🌴</span><span class="wave">〰️〰️〰️〰️〰️</span>';scene.prepend(d);const s=document.createElement('style');s.textContent=`.pirate-decor{position:absolute;inset:0;pointer-events:none;z-index:1;overflow:hidden}.pirate-decor span{position:absolute;filter:drop-shadow(0 3px 3px #002d3c66)}.pirate-decor .sun{top:25px;right:8%;font-size:3rem;opacity:.72}.pirate-decor .bird{top:100px;left:10%;font-size:1.25rem;opacity:.5}.pirate-decor .ship{right:1%;bottom:76px;font-size:6rem;opacity:.82;animation:pirateSail 7s ease-in-out infinite}.pirate-decor .palm{left:1%;bottom:62px;font-size:5rem;opacity:.8}.pirate-decor .wave{left:-10%;right:-10%;bottom:40px;font-size:1.8rem;letter-spacing:10px;opacity:.35;animation:pirateWave 4s linear infinite}@keyframes pirateSail{0%,100%{transform:translateY(0) scaleX(-1)}50%{transform:translateY(-8px) scaleX(-1)}}@keyframes pirateWave{from{transform:translateX(0)}to{transform:translateX(70px)}}.mode-card,.promo,.side-btn,.bottom-btn{transition:transform .16s ease,filter .16s ease}.mode-card:hover{transform:translateY(-5px);filter:brightness(1.03)}.mode-card:active,.promo:active,.side-btn:active,.bottom-btn:active{transform:translateY(2px)}@media(prefers-reduced-motion:reduce){.pirate-decor .ship,.pirate-decor .wave{animation:none}.mode-card,.promo,.side-btn,.bottom-btn{transition:none}}`;document.head.appendChild(s)}
  function installPanelStyle(){if($('piratePanelStyle'))return;const s=document.createElement('style');s.id='piratePanelStyle';s.textContent=`#piratePanel{position:fixed;z-index:200;left:50%;top:50%;transform:translate(-50%,-50%);width:min(720px,calc(100vw - 28px));max-height:78vh;overflow:auto;padding:18px;border:4px solid #b9782d;border-radius:22px;background:linear-gradient(145deg,#fff0bf,#e1b56b);color:#43200f;box-shadow:0 24px 70px #00131dcc,inset 0 0 0 2px #fff7d899}#piratePanel:before{content:'';position:fixed;inset:-200vh;background:#00131d99;z-index:-1}.pp-head{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #9a6129;padding-bottom:10px}.pp-head small{font-weight:900;letter-spacing:.12em;color:#815020}.pp-head h2{margin:2px 0;font-size:1.4rem}.pp-head button{border:2px solid #b87931;border-radius:10px;background:#4d2412;color:#ffe8ac;font-size:1.1rem;padding:6px 10px}.pp-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:13px}.pp-card{padding:12px;border:2px solid #b87931;border-radius:14px;background:#fff5d5;box-shadow:0 4px 0 #744018}.pp-card b{display:block;margin:3px 0}.pp-card small{line-height:1.3}.pp-big{font-size:2rem}.pp-treasure{margin-top:12px}.pp-action{margin-top:10px;border:2px solid #b06b22;border-radius:11px;background:linear-gradient(#24c85d,#087d39);color:#fff7d6;padding:9px 14px;font-weight:900}.pp-action.blue{background:linear-gradient(#25b9ec,#0878ae)}@media(max-width:620px){#piratePanel{padding:13px}.pp-grid{grid-template-columns:1fr 1fr}}@media(max-width:390px){.pp-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
