/* Mahjong Pirate — accueil final type jeu mobile. */
(function(){
  'use strict';
  const KEY='mahjongPirateState';
  const getState=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{};}catch(e){return{};}};
  const startGame=()=>{if(typeof window.newGame==='function'){window.newGame(1);}else{const b=document.querySelector('.mode-card .play');if(b)b.click();}};
  function inject(){
    if(document.getElementById('pirateGameHome'))return;
    const home=document.getElementById('home');
    const scene=home&&home.querySelector('.home-scene');
    if(!home||!scene)return;
    document.body.classList.add('pirate-final-home');
    const style=document.createElement('style');
    style.id='pirate-final-home-css';
    style.textContent=`
      body.pirate-final-home{background:#063e50!important;overflow-x:hidden!important}
      body.pirate-final-home .topbar{display:none!important}
      body.pirate-final-home .shell{max-width:none!important;padding:0!important}
      body.pirate-final-home .captain-card,body.pirate-final-home #arsenalPanel,body.pirate-final-home #missionsPanel{display:none!important}
      body.pirate-final-home #home{min-height:100dvh!important}
      body.pirate-final-home .home-scene{height:100dvh!important;min-height:100dvh!important;padding:0 8px 76px!important;border:0!important;border-radius:0!important;box-shadow:none!important;overflow:hidden!important;background:linear-gradient(180deg,#1aa0ae 0%,#0b7d8e 42%,#07596e 72%,#033d50 100%)!important}
      body.pirate-final-home .home-scene:before{content:'☁️                 ☁️'!important;top:5%!important;left:4%!important;font-size:2.6rem!important;opacity:.25!important;letter-spacing:2rem!important;z-index:1!important}
      body.pirate-final-home .home-scene:after{content:'🌴      〰️〰️〰️      🚢      〰️〰️〰️      🌴'!important;height:105px!important;padding-top:18px!important;font-size:2.8rem!important;background:linear-gradient(transparent,#023342ee)!important;z-index:2!important}
      body.pirate-final-home .logo,body.pirate-final-home .home-layout,body.pirate-final-home .home-bottom{display:none!important}
      #pirateGameHome{position:relative;z-index:10;width:min(1100px,100%);height:100%;margin:auto;display:flex;flex-direction:column}
      .pgh-hud{height:58px;display:grid;grid-template-columns:1fr auto 42px;align-items:center;gap:8px;padding:6px 8px;border:2px solid #d39a3d;border-top:0;border-radius:0 0 17px 17px;background:linear-gradient(#70401f,#2d1308);box-shadow:0 6px 18px #00131dcc;color:#ffe9aa}
      .pgh-profile,.pgh-settings{border:2px solid #c58a36;border-radius:12px;background:linear-gradient(#89532a,#45200f);color:#ffe9ad;box-shadow:0 3px 0 #1e0b05;cursor:pointer}
      .pgh-profile{justify-self:start;display:flex;align-items:center;gap:7px;padding:5px 9px;text-align:left}.pgh-avatar{font-size:1.25rem}.pgh-profile b{display:block;font:900 .72rem Arial}.pgh-profile small{display:block;font:600 .5rem Arial;opacity:.75}.pgh-res{display:flex;gap:6px}.pgh-res span{min-width:68px;padding:6px 8px;border:1px solid #c58a36;border-radius:9px;background:#241008;text-align:center;font:900 .7rem Arial}.pgh-settings{width:38px;height:38px;font-size:1rem}
      .pgh-title{text-align:center;color:#ffe29a;font:900 .58rem Arial;letter-spacing:.2em;text-shadow:0 2px #311208;margin:7px 0 3px}
      .pgh-logo{align-self:center;padding:5px 18px 7px;border:3px solid #d29a3d;border-radius:17px;background:linear-gradient(#8d5529,#3c190c);box-shadow:0 6px 0 #281006,0 10px 22px #00192399;transform:rotate(-1deg);color:#fff0b8;text-align:center}.pgh-logo strong{display:block;font:900 1.75rem Georgia;text-shadow:2px 3px #351208;letter-spacing:.04em}.pgh-logo span{display:inline-block;margin-top:1px;padding:2px 24px;border:2px solid #714018;border-radius:6px;background:#e4bd73;color:#652d12;font:900 .68rem Georgia;letter-spacing:.18em}
      .pgh-map{position:relative;flex:1;min-height:0;margin:4px auto 5px;width:min(1000px,100%);border:3px solid #9d672b;border-radius:30px;background:radial-gradient(circle at 22% 24%,#39b6bb 0 7%,transparent 8%),radial-gradient(circle at 76% 75%,#168f9a 0 9%,transparent 10%),linear-gradient(145deg,#1595a3,#087182 58%,#07566a);box-shadow:inset 0 0 55px #00374699,0 9px 25px #00192399;overflow:hidden}
      .pgh-map:before{content:'✦   ✧             ✦                  ✧   ✦';position:absolute;inset:13px;color:#d5f8f255;font-size:1rem;letter-spacing:1rem;pointer-events:none}.pgh-map:after{content:'〰️〰️〰️〰️〰️〰️〰️';position:absolute;left:-10%;right:-10%;bottom:16%;font-size:1.25rem;opacity:.25;text-align:center;pointer-events:none}
      .pgh-island{position:absolute;z-index:5;display:flex;flex-direction:column;align-items:center;justify-content:center;border:3px solid #b97a30;border-radius:50%;background:radial-gradient(ellipse at 50% 30%,#ffe9a7,#d4a052 74%,#965d26);color:#472313;box-shadow:inset 0 0 0 3px #fff3b066,0 8px 0 #603115,0 13px 22px #00192388;cursor:pointer;transition:.15s transform,.15s filter}.pgh-island:hover{filter:brightness(1.08);transform:translateY(-3px)}.pgh-island b{font:900 1rem Georgia}.pgh-island small{font:900 .52rem Arial;margin-top:2px}.pgh-island .icon{font-size:2.5rem;filter:drop-shadow(2px 4px 2px #4b2815)}.pgh-classic{left:50%;top:29%;transform:translateX(-50%);width:210px;height:160px;box-shadow:0 0 0 5px #f5d36b55,inset 0 0 0 3px #fff3a666,0 10px 0 #603115,0 18px 28px #00192399}.pgh-classic .icon{font-size:3.5rem}.pgh-adventure{left:10%;top:56%;width:145px;height:118px}.pgh-challenge{right:10%;top:58%;width:145px;height:118px}
      .pgh-star{position:absolute;z-index:7;left:50%;top:15%;transform:translateX(-50%);font-size:1.45rem}.pgh-play{position:absolute;z-index:8;left:50%;top:59%;transform:translateX(-50%);min-width:165px;padding:9px 20px;border:3px solid #b96e20;border-radius:15px;background:linear-gradient(#35dc69,#078b40);color:#fff;font:900 .9rem Arial;box-shadow:inset 0 1px #fff7,0 5px 0 #52200d,0 9px 15px #00192388;cursor:pointer}.pgh-play:active{transform:translate(-50%,4px)}
      .pgh-chip{position:absolute;z-index:9;padding:6px 9px;border:2px solid #c88b38;border-radius:11px;background:#30150ce8;color:#ffe5a4;font:900 .58rem Arial;box-shadow:0 4px 0 #1d0b05;cursor:pointer}.pgh-missions{left:12px;top:12px}.pgh-daily{right:12px;top:12px}.pgh-arsenal{left:12px;bottom:12px}.pgh-events{right:12px;bottom:12px}
      .pgh-nav{height:58px;display:grid;grid-template-columns:repeat(5,1fr);gap:4px;padding:4px;border:2px solid #c88b38;border-radius:15px;background:linear-gradient(#693a1b,#291008);box-shadow:0 7px 22px #000b}.pgh-tab{border:1px solid #a96c2a;border-radius:10px;background:transparent;color:#ffe7a8;font:900 .5rem Arial;cursor:pointer}.pgh-tab span{display:block;font-size:1.15rem;margin-bottom:2px}.pgh-tab.active{background:linear-gradient(#d58d35,#713b18);box-shadow:0 0 0 1px #f2cd65,0 3px 0 #281006}
      .pgh-drawer{position:fixed;inset:0;z-index:1000;display:none;background:#00131ddd;backdrop-filter:blur(5px);padding:12px}.pgh-drawer.open{display:block}.pgh-panel{width:min(620px,100%);max-height:calc(100dvh - 24px);overflow:auto;margin:auto;padding:52px 10px 16px;border:3px solid #c98b38;border-radius:20px;background:linear-gradient(#f8e5b5,#dcae61);box-shadow:0 20px 60px #000b;position:relative}.pgh-close{position:absolute;right:10px;top:10px;width:38px;height:38px;border:2px solid #c98b38;border-radius:50%;background:#49220f;color:#ffe7aa;font-weight:900;cursor:pointer}.pgh-panel h2{margin:0 0 10px;color:#4a2614}.pgh-panel .captain-card,.pgh-panel #arsenalPanel,.pgh-panel #missionsPanel{display:block!important;max-width:none!important;margin:0 0 10px!important;box-shadow:none!important}
      @media(max-width:700px){#pirateGameHome{padding:0 1px}.pgh-hud{height:52px;border-radius:0 0 13px 13px}.pgh-profile{padding:4px 6px}.pgh-profile small{display:none}.pgh-profile b{font-size:.6rem}.pgh-avatar{font-size:1.1rem}.pgh-res{gap:3px}.pgh-res span{min-width:52px;padding:5px 4px;font-size:.58rem}.pgh-settings{width:34px;height:34px}.pgh-title{font-size:.45rem;margin:4px 0 1px}.pgh-logo{padding:4px 13px 5px}.pgh-logo strong{font-size:1.35rem}.pgh-logo span{font-size:.54rem;padding:1px 16px}.pgh-map{border-radius:23px;margin-top:2px}.pgh-classic{width:150px;height:116px;top:27%}.pgh-classic .icon{font-size:2.6rem}.pgh-island b{font-size:.83rem}.pgh-island small{font-size:.46rem}.pgh-adventure{left:3%;top:57%;width:106px;height:88px}.pgh-challenge{right:3%;top:59%;width:106px;height:88px}.pgh-adventure .icon,.pgh-challenge .icon{font-size:2rem}.pgh-star{top:12%;font-size:1.1rem}.pgh-play{top:51%;min-width:125px;padding:8px 12px;font-size:.75rem}.pgh-chip{padding:5px 7px;font-size:.48rem}.pgh-missions{left:6px;top:6px}.pgh-daily{right:6px;top:6px}.pgh-arsenal{left:6px;bottom:6px}.pgh-events{right:6px;bottom:6px}.pgh-nav{height:56px}.pgh-tab{font-size:.43rem}.pgh-tab span{font-size:1rem}}
      @media(max-width:390px){.pgh-adventure,.pgh-challenge{width:94px;height:80px}.pgh-adventure{left:1%}.pgh-challenge{right:1%}.pgh-arsenal,.pgh-events{display:none}}
    `;
    document.head.appendChild(style);
    const shell=document.createElement('div');shell.id='pirateGameHome';
    shell.innerHTML=`<header class="pgh-hud"><button class="pgh-profile"><span class="pgh-avatar">🏴‍☠️</span><span><b>Capitaine</b><small>Profil & récompenses</small></span></button><div class="pgh-res"><span>🪙 <b data-pgh="coins">0</b></span><span>💎 <b data-pgh="gems">0</b></span></div><button class="pgh-settings">⚙️</button></header><div class="pgh-title">☠️ CARTE DES CARAÏBES ☠️</div><div class="pgh-logo"><strong>MAHJONG</strong><span>PIRATES</span></div><main class="pgh-map"><div class="pgh-star">⭐</div><button class="pgh-chip pgh-missions">📜 Missions</button><button class="pgh-chip pgh-daily">🎁 Défi du jour</button><button class="pgh-island pgh-classic"><span class="icon">🀄</span><b>CLASSIQUE</b><small>ÎLE PRINCIPALE</small></button><button class="pgh-play">⚓ JOUER</button><button class="pgh-island pgh-adventure"><span class="icon">🗺️</span><b>AVENTURE</b><small>EXPLORER</small></button><button class="pgh-island pgh-challenge"><span class="icon">☠️</span><b>DÉFIS</b><small>RELEVER</small></button><button class="pgh-chip pgh-arsenal">🧰 Arsenal</button><button class="pgh-chip pgh-events">🎉 Événements</button></main><nav class="pgh-nav"><button class="pgh-tab active"><span>🏠</span>Accueil</button><button class="pgh-tab pgh-map-tab"><span>🗺️</span>Carte</button><button class="pgh-tab pgh-mission-tab"><span>🎯</span>Défis</button><button class="pgh-tab pgh-shop-tab"><span>💎</span>Boutique</button><button class="pgh-tab pgh-profile-tab"><span>👤</span>Profil</button></nav></div>`;
    scene.appendChild(shell);
    const drawer=document.createElement('div');drawer.className='pgh-drawer';drawer.innerHTML='<div class="pgh-panel"><button class="pgh-close" type="button">✕</button><h2>🏴‍☠️ Quartier du capitaine</h2></div>';document.body.appendChild(drawer);
    const panel=drawer.querySelector('.pgh-panel');
    function collect(){['.captain-card','#arsenalPanel','#missionsPanel'].forEach(sel=>{const el=document.querySelector(sel);if(el&&!panel.contains(el))panel.appendChild(el);});}
    function openDrawer(){collect();drawer.classList.add('open');}
    function closeDrawer(){drawer.classList.remove('open');}
    shell.querySelector('.pgh-profile').onclick=openDrawer;shell.querySelector('.pgh-settings').onclick=openDrawer;shell.querySelector('.pgh-missions').onclick=openDrawer;shell.querySelector('.pgh-arsenal').onclick=openDrawer;shell.querySelector('.pgh-profile-tab').onclick=openDrawer;shell.querySelector('.pgh-close')?.addEventListener('click',closeDrawer);drawer.querySelector('.pgh-close').onclick=closeDrawer;drawer.onclick=e=>{if(e.target===drawer)closeDrawer();};
    shell.querySelector('.pgh-play').onclick=startGame;shell.querySelector('.pgh-classic').onclick=startGame;
    shell.querySelector('.pgh-adventure').onclick=()=>alert('🗺️ Aventure : les nouvelles îles arrivent bientôt.');shell.querySelector('.pgh-challenge').onclick=()=>alert('☠️ Défis : prépare ton équipage !');shell.querySelector('.pgh-daily').onclick=openDrawer;shell.querySelector('.pgh-mission-tab').onclick=openDrawer;shell.querySelector('.pgh-shop-tab').onclick=openDrawer;shell.querySelector('.pgh-map-tab').onclick=()=>alert('🗺️ Carte des Caraïbes');
    function refresh(){const s=getState();shell.querySelector('[data-pgh="coins"]').textContent=Number(s.coins)||0;shell.querySelector('[data-pgh="gems"]').textContent=Number(s.gems)||0;}
    refresh();
    setTimeout(collect,300);setTimeout(refresh,800);setTimeout(collect,1200);
  }
  function boot(){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject,{once:true});else inject();}
  boot();
})();
