/* Progression pirate : coffres + bonus consommables + barre XP. */
(function(){
 const css=document.createElement('style');css.textContent=`.pirate-progression{margin-top:12px;max-width:620px}.xp-track{height:9px;border-radius:99px;background:#062f3d;border:1px solid #d4a34c66;overflow:hidden}.xp-fill{height:100%;width:0;background:linear-gradient(90deg,#d39b3b,#f5d46b);transition:width .35s}.xp-foot{display:flex;justify-content:space-between;font-size:.72rem;color:#bfd6d3;margin-top:4px}.treasure-tools{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.treasure-tools button{border:1px solid #d4a34c;background:#173f4b;color:#f7e8b5;border-radius:9px;padding:6px 9px;font-weight:800;cursor:pointer}.bonus-strip{display:flex;gap:7px;flex-wrap:wrap;margin:0 0 12px}.bonus-chip{background:#062f3d99;border:1px solid #d4a34c55;color:#f5e3aa;border-radius:999px;padding:6px 10px;font-size:.78rem;font-weight:800}.chest-modal{border:2px solid #d4a34c;border-radius:20px;background:radial-gradient(circle at 50% 0,#7b4a20,#3b2113 75%);color:#fff;text-align:center;padding:28px;max-width:400px;box-shadow:0 20px 60px #000b}.chest-modal::backdrop{background:#00151dcc}.chest-icon{font-size:3.4rem;filter:drop-shadow(0 5px 5px #0008);animation:chestBob 1.7s ease-in-out infinite}@keyframes chestBob{50%{transform:translateY(-5px) rotate(-2deg)}}`;document.head.appendChild(css);
 const card=document.querySelector('.captain-card');if(!card)return;
 state.chests=Number(state.chests)||0;state.bonusHints=Number(state.bonusHints)||0;state.bonusShuffles=Number(state.bonusShuffles)||0;
 const info=document.createElement('div');info.className='pirate-progression';info.innerHTML=`<div class="xp-track"><div id="xpBar" class="xp-fill"></div></div><div class="xp-foot"><span id="xpNext">100 XP</span><span>🏴‍☠️ Progression du capitaine</span></div><div class="treasure-tools"><button id="openChest" type="button">🧰 Coffres <b id="chestCount">0</b></button></div>`;card.firstElementChild.appendChild(info);
 const actions=document.querySelector('.actions');if(actions){const strip=document.createElement('div');strip.className='bonus-strip';strip.innerHTML=`<span class="bonus-chip">🧭 Boussoles : <b id="bonusHintCount">0</b></span><span class="bonus-chip">🔀 Cartes chanceuses : <b id="bonusShuffleCount">0</b></span>`;actions.parentNode.insertBefore(strip,actions)}
 const dialog=document.createElement('dialog');dialog.id='chest';dialog.className='chest-modal';dialog.innerHTML=`<div class="chest-icon">🧰</div><h2>Coffre du capitaine</h2><p id="chestText">Un trésor attend ton équipage.</p><div class="reward"><span>🪙 <b id="chestCoins">0</b></span><span>💎 <b id="chestGems">0</b></span><span>⭐ <b id="chestXp">0</b> XP</span></div><p id="chestBonus"></p><div class="modal-actions"><button id="claimChest" type="button">Ouvrir un coffre</button><button id="closeChest" class="ghost" type="button">Fermer</button></div>`;document.body.appendChild(dialog);
 function refresh(){const xpNext=Math.max(100,state.level*100),base=Math.max(0,(state.level-1)*100),cur=Math.max(0,state.xp-base),pct=state.level>=5?100:Math.min(100,cur/xpNext*100);$('xpBar').style.width=pct+'%';$('xpNext').textContent=state.level>=5?'Niveau maximum atteint':`${Math.max(0,xpNext-cur)} XP pour le niveau ${state.level+1}`;$('chestCount').textContent=state.chests;$('bonusHintCount').textContent=state.bonusHints;$('bonusShuffleCount').textContent=state.bonusShuffles}
 function openChest(){if(!state.chests){$('chestText').textContent='Aucun coffre disponible. Termine une île pour en gagner.';$('chestCoins').textContent=0;$('chestGems').textContent=0;$('chestXp').textContent=0;$('chestBonus').textContent='';$('claimChest').textContent='Compris';$('chest').showModal();return}state.chests--;const coins=30+Math.floor(Math.random()*51),gems=Math.random()<.2?1:0,xp=20+Math.floor(Math.random()*31);state.coins+=coins;state.gems+=gems;state.xp+=xp;let bonus;if(Math.random()<.5){state.bonusHints++;bonus='🧭 +1 Boussole — indice gratuit';}else{state.bonusShuffles++;bonus='🔀 +1 Carte chanceuse — mélange gratuit';}while(state.level<5&&state.xp>=state.level*100)state.level++;$('chestText').textContent='✨ Trésor découvert !';$('chestCoins').textContent=coins;$('chestGems').textContent=gems;$('chestXp').textContent=xp;$('chestBonus').textContent=bonus;save();refresh();sfx(true);$('chest').showModal()}
 $('openChest').onclick=openChest;$('claimChest').onclick=openChest;$('closeChest').onclick=()=>$('chest').close();
 const oldSave=save;save=function(){oldSave();refresh()};
 const oldWin=win;win=function(){oldWin();const stars=($('stars').textContent.match(/★/g)||[]).length,extra=stars===3?2:1;state.chests+=extra;$('winText').textContent+=' 🧰 '+extra+' coffre'+(extra>1?'s':'')+' gagné'+(extra>1?'s':'')+' !';save();refresh()};
 const oldHint=hint;hint=function(){if(game&&legalPairs().length&&state.bonusHints>0){const pair=legalPairs()[0];game.selected=pair[0].id;state.bonusHints--;render();$('msg').textContent=`🧭 Boussole : ${pair[0].symbol} peut être associé à une autre tuile libre.`;save()}else oldHint()};
 const oldShuffle=shuffle;shuffle=function(){if(game&&state.bonusShuffles>0){state.bonusShuffles--;const active=game.tiles.filter(t=>!t.removed),original=active.map(t=>t.symbol);let ok=false;for(let attempt=0;attempt<80&&!ok;attempt++){const syms=[...original].sort(()=>Math.random()-.5);active.forEach((t,i)=>t.symbol=syms[i]);ok=legalPairs().length>0}if(!ok)active.forEach((t,i)=>t.symbol=original[i]);game.combo=0;game.selected=null;render();$('msg').textContent=ok?'🔀 Carte chanceuse : mélange gratuit !':'🔀 Mélange conservé.';save();timer=setInterval(tick,500)}else oldShuffle()};
 $('hint').onclick=hint;$('shuffle').onclick=shuffle;$('deadlockShuffle').onclick=shuffle;
 refresh();
})();
